### ISSUE TITLE
New bootstrap-3 theme for luci2

### ISSUE THREAD

**Issue by kumarrishav** [sudomesh/sudowrt-web-ui#3]
Is there anyway to work on new theme, i.e how to build it and text the existing theme and get an idea of, how to work on new theme. Is this repo working or anyway to work on building theme for luci2 Please help.

**Comment by max-b** [comment]
Hey - so if you follow the directions in the readme you can see what we've got so far and do any theme building you want:

```
npm install
node server.js
```

Should be as simple as that assuming you have node installed.

**Comment by kumarrishav** [comment]
Thanks @max-b  :)  It's running fine but there is no functionality and other pages are dashboard.html,footer.html are empty. Can you please port current theme of luci here in this, it will helpful in understanding current luci. I was unable to run luci on my system and suddenly i found this. I expect  this will be helpful.

**Comment by max-b** [comment]
hey @kumarrishav that's not really what we're trying to do here. LUCI is a completely different platform, the only thing these two share is the name. If you're trying to get an web admin page running on an openwrt device, you should stick to LUCI for now. There are stock openwrt packages for that over at the openwrt downloads site.
