### ISSUE TITLE
Setting too short a password for private wifi disables the network with no error

### ISSUE THREAD

**Issue by stephens2424** [sudomesh/sudowrt-web-ui#8]
I set a password for the private wifi network and it didn't give me an error. The network disappeared and then I realized the password was probably too short (I know, bad). I changed the password to something longer and the SSID started showing up in devices' lists again.

**Comment by max-b** [comment]
Ah yeah that's a good point. It would be pretty easy to add validators to https://github.com/sudomesh/sudowrt-web-ui/blob/master/web-src/js/section-configs.js which would then be called somewhere around https://github.com/sudomesh/sudowrt-web-ui/blob/master/web-src/js/dashboard-store.js#L160 in the `setting_changed` handler.

I'm not really working on sudomesh right now, so I can't really promise any quick action, but seeing as I wrote the thing so far, I should be able to get to it eventually.

**Comment by jhpoelen** [comment]
sudowrt-web-ui no longer used
